name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - release

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show Trigger Information
        run: |
          echo "Pipeline Triggered!"
          echo "Source Branch (PR From): ${{ github.head_ref }}"
          echo "Target Branch (PR To): ${{ github.base_ref }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Repository: ${{ github.repository }}"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
      
      # - name: Run Lint
      #   run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: List build output (debug)
        run: ls -R

#   sonarqube:
#     name: SonarQube Scan and Quality Gate
#     runs-on: ubuntu-latest
#     needs: test-and-build

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Run SonarQube Scan
#         uses: SonarSource/sonarqube-scan-action@v6
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
#         with:
#           projectBaseDir: frontend
#           args: >
#             -Dsonar.projectKey=Frontend-Application
#       - name: Debug Sonar Files
#         run: |
#           find . -name "report-task.txt"

#       - name: Check SonarQube Quality Gate
#         uses: SonarSource/sonarqube-quality-gate-action@v1
#         with:
#           scanMetadataReportFile: frontend/.scannerwork/report-task.txt
#         timeout-minutes: 10
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

# # done 
# #  new done